### ISSUE TITLE
UI error on Tag Der Toten

### ISSUE THREAD

**Issue by c0mpile** [MrFawkes1337/BO4-Lucy-Menu#2]
When using the option to open all doors, a UI error comes up and you're no longer able to open barricades. None of the barricades on the map open with the function so that's a problem. The text of the error is "Whiskey 110 Late Tiger".

**Comment by MrFawkes1337** [comment]
Yup, I still need to address that issue, its on all maps, and its down to the Open All Doors the guy used being a direct Copy paste from Black Ops 3, and not having all the values required. It's on the list, and I'll be looking soon! Thanks for the bug report :D.

**Comment by MrFawkes1337** [comment]
Please downloaded latest Push, this issue is now fixed. :D
